# Generated by Django 3.0.2 on 2020-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')])),
                ('batch', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first', models.ManyToManyField(related_name='first', to='scores.Athlete')),
                ('second', models.ManyToManyField(related_name='second', to='scores.Athlete')),
                ('third', models.ManyToManyField(related_name='third', to='scores.Athlete')),
            ],
        ),
    ]
