# Generated by Django 3.0.2 on 2020-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='first_points',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='second_points',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='third_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
